### ISSUE TITLE
Feature Request: Use configured resolvers

### ISSUE THREAD

**Issue by CodeMonk** [bschaatsbergen/dnsee#1]
My company blocks google dns for some reason, so I can't get to 8.8.8.8. It would be nice to either have an option to use the DNS resolvers already configured, if not make it the default.

Would also help if you're running local DNS for unroutable IPs that wouldn't show up on google's DNS.

**Comment by CodeMonk** [comment]
> Thanks for raising this issue @CodeMonk, I'm happy to take a stab at this. For now you could optionally provide the '--dns-server-ip' to bypass this issue?

Absolutely -- I did that to try it out and I liked the results -- hence the feature request to make it easier for me to type int he future ;-)

Great work on it. I prefer it already to `dig` and `nslookup`!

**Comment by bschaatsbergen** [comment]
Hi @CodeMonk, this has been addressed by @mmourick in #3. Please note that it only works on posix systems (fetching the local DNS resolver) as Windows has a terrible interface to fetch the DNS resolver, if you're using Windows please set the `dns-server-ip` flag.

**Comment by CodeMonk** [comment]
Thank you @mmourick and @bschaatsbergen ;-)
