### ISSUE TITLE
`dnsee` outputs TTL values in an unclear way

### ISSUE THREAD

**Issue by mmourick** [bschaatsbergen/dnsee#23]
The TTL values should be more recognizable in the output of `dnsee`.  Consider changing the current output from
```
A	google.com.	71	172.217.23.206
AAAA	google.com.	204	2a00:1450:400e:80f::200e
MX	google.com.	123	10	smtp.google.com.
....
``` 
to the output below (or similar)
```
A	google.com.	71 (TTL)	172.217.23.206
AAAA	google.com.	204 (TTL)	2a00:1450:400e:80f::200e
MX	google.com.	123 (TTL)	10	smtp.google.com.
```

**Comment by bschaatsbergen** [comment]
Optionally we could consider a heading, as you coined earlier @mmourick

**Comment by bschaatsbergen** [comment]
I'll pick this up

**Comment by mmourick** [comment]
After giving it some more thought, I think parsing the TTL values to more human friendly values (e.g. minutes and seconds) will immediately make it clear that the particular column concerns TTL values while keeping the output of `dnsee` clean and minimalistic.

**Comment by bschaatsbergen** [comment]
That's an awesome idea, and in-line with our vision for dnsee.
