### ISSUE TITLE
dial udp: address `1004:520:4e42:2000::53:53:` too many colons in address

### ISSUE THREAD

**Issue by bschaatsbergen** [bschaatsbergen/dnsee#26]
When running: `dnsee bschaatsbergen.com`

I get the following error: `dial udp: address 1004:520:4e42:2000::53:53: too many colons in address`

**Comment by mmourick** [comment]
Seems like the issue only appears when querying a DNS server through IPv6.
Will do a more thorough investigation and make a fix.

**Comment by bschaatsbergen** [comment]
It is probable that this issue arises because my resolve configuration uses an IPv6 address to issue DNS queries, that already includes ":53." Based on https://github.com/bschaatsbergen/dnsee/blob/main/pkg/core/core.go#L52-L66, it seems that we now always append ":53" to the DNS server IP by default... @mmourick
