### ISSUE TITLE
Allow port specification via `--dns-server-ip`

### ISSUE THREAD

**Issue by bschaatsbergen** [bschaatsbergen/dnsee#31]
**Feature request:**
Currently, the `--dns-server-ip` flag allows users to specify a custom DNS server IP address. However, it would be nice to extend this functionality by enabling users to also specify a port along with the IP address.

**Motivation:** 
In scenarios where custom DNS servers operate on non-default ports, users need the ability to define both the IP address and port number. This feature would enhance the flexibility and utility of the `--dns-server-ip` flag, accommodating a wider range of network configurations.

**Proposed solution:**
Introduce a syntax extension for the `--dns-server-ip` flag that allows users to specify both IP address and port, for example:

```
dnsee --dns-server-ip ipv4
dnsee --dns-server-ip ipv4:port
dnsee --dns-server-ip ipv6
dnsee --dns-server-ip [ipv6]:port
```

**Note** the brackets around the IPv6 IP address when specifying a port, this is because IPv6 addresses contain colons, and URLs use colons to separate the host from the port number, RFC2732[[41]](https://en.wikipedia.org/wiki/IPv6#cite_note-41) specifies that an IPv6 address used as the host-part of a URL should be enclosed in square brackets, e.g. http://[2001:db8:4006:812::200e] or http://[2001:db8:4006:812::200e]:8080/path/page.html.

**Comment by kvanzuijlen** [comment]
I can take a crack at this if you want @bschaatsbergen

**Comment by bschaatsbergen** [comment]
Check with @mmourick, as I just supplied him with some feedback on #30
